# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/phatle/ProcessorDesign/ProcessorDesign.cache/wt [current_project]
set_property parent.project_path C:/Users/phatle/ProcessorDesign/ProcessorDesign.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/phatle/ProcessorDesign/ProcessorDesign.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/lab8.dat
read_verilog -library xil_defaultlib {
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/CMP.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/CNT.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/ControlUnit.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/DataPath.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/Factorial.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/GPIO_ad.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/MUL.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/new/REG.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/SRreg.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/System.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/adder.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/alu.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/auxdec.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/imports/basys3_utility_modules/clk_gen.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/controlunit.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/datapath.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/memory/dmem.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/dreg.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/fact_ad.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/fact_top.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/basys3_single_cycle_mips_validation/hex_to_7seg.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/memory/imem.v
  C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/imports/basys3_utility_modules/led_mux.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/control_unit/maindec.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/mips/mips.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/multu.v
  {C:/Users/phatle/Lab1-Factorial/Lab1-Factorial.srcs/sources_1/imports/Full Calculator Data Path/mux2.v}
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/mux2.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/mux3.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/pqio_top.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/regfile.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/imports/single_cycle_mips_source_initial/datapath/signext.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/soc_ad.v
  C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/sources_1/new/soc_FPGA.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/constrs_1/new/soc_fpga.xdc
set_property used_in_implementation false [get_files C:/Users/phatle/ProcessorDesign/ProcessorDesign.srcs/constrs_1/new/soc_fpga.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_FPGA -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_FPGA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_FPGA_utilization_synth.rpt -pb soc_FPGA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
